# Generated by Django 4.1.6 on 2023-02-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('memorial', 'Memorial'), ('nonprofit', 'Nonprofit'), ('financial-emergency', 'Financial Emergency'), ('environment', 'Environment'), ('animals', 'Animals'), ('business', 'Business'), ('community', 'Community'), ('competition', 'Competition'), ('creative', 'Creative'), ('event', 'Event'), ('faith', 'Faith'), ('family', 'Family'), ('sports', 'Sports'), ('travel', 'Travel'), ('volunteer', 'Volunteer'), ('wishes', 'Wishes')], max_length=100),
        ),
    ]
