# Generated by Django 4.1.6 on 2023-02-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_campaign_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='links',
        ),
        migrations.AddField(
            model_name='campaign',
            name='link',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
