# Generated by Django 4.1.6 on 2023-02-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_campaign_links_campaign_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='about',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
