# Generated by Django 4.1.6 on 2023-02-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='goal_date',
        ),
    ]
